// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Counter: typeof import('./components/Counter.vue')['default']
    Footer: typeof import('./components/Footer.vue')['default']
    KButton: typeof import('./components/KButton.vue')['default']
    LineLiff: typeof import('./components/LineLiff.vue')['default']
    Navbar: typeof import('./components/Navbar.vue')['default']
    NavBar: typeof import('./components/NavBar.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
  }
}

export {}
